services:
  # 🌐 SERVIDOR BACKEND (API)
  - type: web
    name: evidence-management-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: "admin_super_secret_key_123"
      - key: DB_HOST
        value: gateway01.us-east-1.prod.aws.tidbcloud.com
      - key: DB_USER
        value: 2vMVrSXioiJYE4q.root
      - key: DB_PASSWORD
        value: kkV43Tcfet5mqqqb
      - key: DB_NAME
        value: test
      - key: DB_PORT
        value: "4000"
      - key: DB_SSL
        value: "true"
    healthCheckPath: /

  # 🖥️ SITIO FRONTEND (Angular)
  - type: web
    name: evidence-management-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build:prod
    # Usamos npx serve para servir la carpeta correcta y evitar el 404
    startCommand: npx serve -s frontend/dist/proyecto_inicial/browser -p 8080
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8080
      - key: API_BASE_URL
        value: https://evidence-management-backend.onrender.com
